app/app/finance/models.py
from datetime import datetime
from sqlalchemy.dialects.mysql import LONGTEXT
from sqlalchemy import JSON
from .. import db, login_manager

from .business import calculate_charge_rule, calculate_reduce_charge



class Transaction(db.Model):
    __tablename__ = 'transactions'
    id = db.Column(db.BigInteger, primary_key=True)
    # body = db.Column(LONGTEXT)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    amount = db.Column(db.Integer)
    currency = db.Column(db.String(64), default='IRT')
    description = db.Column(db.Text)
    created_at = db.Column(db.DateTime, index=True, default=datetime.now)
    
    @classmethod
    def create_charge_transaction(cls, user_id: int, amount: int, description='Charge user by bank'):
        obj = cls(user_id=user_id, amount=amount, description=description)
        db.session.add(obj)
        db.session.commit()
        return obj


class Bank(db.Model):
    __tablename__ = 'banks'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    slug = db.Column(db.String(64), unique=True)
    name = db.Column(db.String(64))
    logo_url = db.Column(db.Text)
    api_key = db.Column(db.Text)
    description = db.Column(db.Text)
    
    
    created_at = db.Column(db.DateTime,default=datetime.now)
    updated_at = db.Column(db.DateTime,default=datetime.now, onupdate=datetime.now)
    
    
    @classmethod 
    def get_bank_by_slug(cls, slug):
        return cls.query.filter_by(slug=slug).first()
    
        
    

class Receipt(db.Model):
    __tablename__ = 'receipts'
    # STATUSES: pending, success, failed
    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.String(128), unique=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    bank_id = db.Column(db.Integer, db.ForeignKey('banks.id'))
    transaction = db.Column(db.BigInteger, db.ForeignKey('transactions.id'), nullable=True)
    currency = db.Column(db.String(64), default='IRT')
    amount = db.Column(db.Integer)
    status = db.Column(db.String(64))
    tracker_id = db.Column(db.String(64))
    
    description = db.Column(db.Text)
    additional_data = db.Column(JSON, default=dict)  # JSON column with default value
    
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    
    
    @classmethod
    def create_receipt(cls, user_id, amount, bank_id):
        number = datetime.now().strftime("%Y%m%d%H%M%S")
        obj = cls(number=number, 
                  user_id=user_id, 
                  amount=amount, 
                  bank_id=bank_id,
                  status='pending'
                  )
        db.session.add(obj)
        return obj

    def update_additional_data(self, new_data):
        if not isinstance(new_data, dict):
            raise ValueError("new_data must be a dictionary")
       
        if self.additional_data is None:
            self.additional_data = {}
        data = self.additional_data.copy()
        data.update(new_data)
        self.additional_data = data
        db.session.commit()
        return self
    
    def set_status(self, status='success'):
        self.status = status
        db.session.commit()
        return self
    
    def set_tracker_id(self, tracker_id):
        self.tracker_id = tracker_id
        db.session.commit()
        return self
    
    def add_transaction(self, bank_slug='zibal', description=''):
        bank = Bank.query.filter_by(slug=bank_slug).first()
        self.bank_id = bank.id
        # Add transaction for user
        Transaction.create_charge_transaction(user_id=self.user_id, 
                                              amount=self.amount, 
                                              description='User charges for {} [{}]'.format(self.tracker_id, description))
        # To have system balance, add another transaction for bank
        
        Transaction.create_charge_transaction(user_id=bank.user_id, 
                                              amount=self.amount * -1, 
                                              description='Payment {} [{}]'.format(self.tracker_id, description))
        
        db.session.commit()
        return self


class Charge(db.Model):
    __tablename__ = 'charges'
    id = db.Column(db.BigInteger, primary_key=True)
    
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    content_id = db.Column(db.Integer, db.ForeignKey('contents.id'))
    word_count = db.Column(db.Integer)
    description = db.Column(db.Text)
    created_at = db.Column(db.DateTime, index=True, default=datetime.now)
    
    
    @classmethod
    def add_user_charge(cls, user_id, toman_amount, description=''):
        total_words = calculate_charge_rule(toman_amount)
        obj = cls(user_id=user_id,
                  word_count=total_words,
                  description=description)
        db.session.add(obj)
        db.session.commit()
        return obj

    @classmethod
    def reduce_user_charge(cls, user_id, total_words, model='gpt-3.5', content_id=None):
        if total_words < 0:
            total_words = -1 * total_words
        total_words = calculate_reduce_charge(total_words, model=model)
        obj = cls(user_id=user_id,
                  word_count=total_words * -1,
                  content_id=content_id)
        db.session.add(obj)
        db.session.commit()
        return obj
    
    @classmethod
    def get_user_charge(cls, user_id):
        total_word_count = db.session.query(db.func.sum(cls.word_count)).filter_by(user_id=user_id).scalar()
        return total_word_count if total_word_count is not None else 0

app/app/finance/forms.py
from flask_wtf import FlaskForm
from wtforms import DecimalField, SubmitField
from wtforms.validators import DataRequired

class CreatePayForm(FlaskForm):
    amount = DecimalField('Amount', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/app/finance/__init__.py
from flask import Blueprint

finance = Blueprint('finance', __name__)

from . import views

app/app/finance/views.py
from flask import render_template, redirect, request, url_for, flash, jsonify
from flask_login import login_user, logout_user, login_required, \
    current_user
from . import finance
from .. import db
from .models import Receipt, Bank, Charge
from .forms import CreatePayForm
from flask_login import login_required, current_user

import os

from persian_tools import digits, separator

import logging
logger = logging.getLogger()

import zibal.zibal as zibal

merchant_id = os.environ.get('ZIBAL_MERCHAND_ID', 'zibal') # zibal for test mode
callback_url = os.environ.get('ZIBAL_CALLBACK_URL', 'http://127.0.0.1:5000/finance/webhook/zibal')
START_PAYMENT_URL = 'https://gateway.zibal.ir/start/'
MAIN_URL = os.environ.get('MAIN_URL', 'http://127.0.0.1:5000')


def create_pay_service(user, amount) -> dict:
    logger.info('Requested amount for user {} is {}'.format(user.id, amount))
    
    bank = Bank.get_bank_by_slug('zibal')
    receipt = Receipt.create_receipt(user_id=user.id, amount=amount, bank_id=bank.id)
    
    zb = zibal.zibal(merchant_id, callback_url)
    description = 'خرید شارژ به میزان {} ریال'.format(amount * 10)  # Amount is in RIAL !!!!!
    
    request_to_zibal = zb.request(amount=amount * 10, 
                                  description=description, 
                                  order_id=receipt.number)
    logger.info('Zibal request data {}'.format(request_to_zibal))
    
    if request_to_zibal.get('message') != 'success':
        return jsonify({'error': 'Zibal request is not successful'}), 500
    
    receipt.update_additional_data({'request_to_zibal': request_to_zibal})
    receipt.set_tracker_id(str(request_to_zibal.get('trackId')))
    redirect_url = START_PAYMENT_URL + str(request_to_zibal.get('trackId'))
    logger.info(redirect_url)
    
    return {'redirect_url': redirect_url, 'receipt': receipt}



@finance.route('/finance/create_pay', methods=['GET', 'POST'])
@login_required
def create_pay():
    form = CreatePayForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = current_user
        amount = float(form.amount.data)
        redirect_dict = create_pay_service(user=user, amount=amount)
        return redirect(redirect_dict['redirect_url'])
                
    return render_template('finance/create_pay.html', form=form)


@finance.route('/finance/webhook/zibal', methods=['GET'])
# @login_required
def zibal_webhook():
    track_id = request.args.get('trackId')
    success = request.args.get('success')
    status = request.args.get('status')
    order_id = request.args.get('orderId')
    
    if not track_id or not success or not status:
        flash('Invalid callback parameters', 'danger')
        return render_template('finance/status_page.html')
    
    # Check receipt be pending and exists
    logger.info('Incoming track id ' + str(track_id))
    receipt = Receipt.query.filter_by(tracker_id=str(track_id)).first()
    logger.info('Found receipt : {}'.format(receipt))
    if not receipt or receipt.status != 'pending':
        flash('Receipt not found or has not been pending', 'danger')
        return render_template('finance/status_page.html')
    
    if status == '1':
        receipt.set_status('failed')
        flash('پرداخت شما قبلا داخل سیستم نشسته است', 'danger')
        return render_template('finance/status_page.html')
    
    # Check status be success 1: success, 0: failed
    if status != '2':
        receipt.set_status('failed')
        flash('پرداخت شما موفقیت امیز نبود', 'danger')
        return render_template('finance/status_page.html')
    
    logger.info('Adding the additional data')
    # Check receipt
    receipt.update_additional_data({'call_back_data': request.args.to_dict()})
    receipt.add_transaction(bank_slug='zibal', description='Success')
    receipt.set_status('success')
    
    logger.info(f'Charge user {receipt.user_id} -> {receipt.amount}')
    # Add user charge (see finance.business about charge business and rules)
    user_new_charge = Charge.add_user_charge(user_id=receipt.user_id, toman_amount=receipt.amount)
    
    logger.info(f'Going to verify the payment {track_id} -> {receipt.user_id}')
    # Verify it
    zb = zibal.zibal(merchant_id, callback_url)
    verify_zibal = zb.verify(track_id)
    verify_result = verify_zibal['result']
    logger.info('Verify result {}'.format(verify_result))
    receipt.update_additional_data({'verify_result': verify_result})
    if receipt.additional_data.get('redirect_url'):
        return redirect(receipt.additional_data.get('redirect_url'))
    
    return redirect(MAIN_URL + '/finance/status?receipt_number={}&user_charge={}'.format(receipt.number, user_new_charge.word_count))


@finance.route('/finance/status', methods=['GET'])
@login_required
def payment_status():
    receipt_number = request.args.get('receipt_number')
    receipt_number = digits.convert_to_fa(receipt_number)
    charge = request.args.get('user_charge')
    charge = digits.convert_to_fa(charge)
    charge = separator.add(charge)
    flash('اکانت شما به شماره تراکنش {} در سیستم ثبت شد. تعداد {} کلمه اکانت شما شارژ شد'.format(receipt_number, charge), 'success')
    return render_template('finance/status_page.html')

app/app/templates/finance/create_pay.html
{% extends "base.html" %}
{% block content %}

<div class="container mr-auto mx-auto" style="max-width: 960px;">
    <div class="dashboard-card d-flex flex-md-column align-items-start justify-content-start p-4" style="min-height: 65vh;">
        <div style="min-height: 65vh;" class="w-100 row">
            <div class="col-md-7 rounded bg-white p-4 text-justify">
                <h5>
                    افزایش اعتبار 
                </h5>
                <p class="mt-4">            در این بخش می‌توانید اعتبار مورد نیاز خود را به صورت تعداد کلمه خریداری کنید و با استفاده از این اعتبار از سرویس‌ها و ابزارهای مختلف ما بهره‌مند شوید. 
                </p>
                <p>
                    توجه داشته باشید که در هر بخش از این سرویس، مدل‌های مختلفی به شما پیشنهاد می‌شود که ضریب استفاده از کلمات آنها متفاوت است. این مدل‌ها بر اساس سطح هوشمندی خود دارای هزینه‌های مختلفی هستند که از طریق ضریب استفاده از کلمات تعیین می‌شود.
    
                </p>
    
                <div style="width: 350px;" class="mr-auto mx-auto">
                    <lottie-player src="{{ url_for('static', filename='media/payment.json') }}"
                    background="transparent" speed="1" loop autoplay></lottie-player>                
                </div>
            </div>
    
            <div class="col-md-5 rounded bg-white p-4 mt-4">
    
                <div class="d-flex justify-content-evenly mb-4 mt-4">
                    <div class="text-center">
                        <span class="badge badge-primary text-dark"> کلمه</span>
                        <div id="rangeThumb" class="range-thumb rounded p-2 bg-light fs-4" style="right: 0%;">۲۰۰۰</div>
                    </div>
                    <div class="text-center">
                        <span class="badge badge-primary text-dark"> قیمت هر کلمه</span>
                        <div id="pricePerWord" class="text-muted rounded p-2 bg-light fs-4"> ۲۰
                        </div>
                    </div>
                </div>
    
                <div class="range-slider mb-4 text-center mt-4 pt-4">
                    <label for="wordCountSlider" class="form-label">تعداد کلمات مورد نیاز</label>
                    <input id="wordCountSlider" type="range" class="form-range" min="2000" max="100000" value="2000"
                        step="100" oninput="updatePrice()">
                </div>
    
                <div class="text-center mt-4 pt-4">
                    <span class="badge badge-primary text-dark"> جمع</span>
                    <div id="total" class="font-weight-bold fs-4">۴۰٬۰۰۰ تومان</div>
                </div>
    
                <div class="text-center mt-4">
                    <form method="POST" action="{{ url_for('finance.create_pay') }}">
                        {{ form.hidden_tag() }}
                        <input type="hidden" id="amount" name="amount" value="0">
                        <button type="submit" class="btn btn-primary w-50 text-white">خرید</button>
                    </form>
                </div>
            </div>
        </div>
    
    </div>
    
</div>

<script>
    function updatePrice() {
        const rangeValue = document.getElementById('wordCountSlider').value;
        let pricePerWord;

        if (rangeValue <= 19999) {
            pricePerWord = 3;
        } else if (rangeValue <= 39999) {
            pricePerWord = 2.9;
        } else if (rangeValue <= 59999) {
            pricePerWord = 2.8;
        } else if (rangeValue <= 79999) {
            pricePerWord = 2.7;
        } else {
            pricePerWord = 2.5;
        }

        const totalPrice = rangeValue * pricePerWord;
        document.getElementById('pricePerWord').textContent = `${pricePerWord.toLocaleString('fa-IR')}`;
        document.getElementById('total').textContent = `${totalPrice.toLocaleString('fa-IR')} تومان`;
        document.getElementById('rangeThumb').style.right = `${((rangeValue - 2000) / 98000) * 100}%`;
        document.getElementById('rangeThumb').textContent = parseInt(rangeValue).toLocaleString('fa-IR');
        document.getElementById('amount').value = totalPrice;
    }

    document.addEventListener('DOMContentLoaded', () => {
        updatePrice();
    });
</script>



{% endblock %}

app/app/templates/finance/status_page.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-5 mr-auto mx-auto p-3 rounded bg-white dashboard-card" style="max-width: 960px;">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="alert alert-{{ messages[0][0] }} float-left" role="alert">
                {{ messages[0][1] }}
            </div>
        {% endif %}
    {% endwith %}
    <!-- Additional content for the status page can go here -->
</div>


{% endblock %}